server:
  port: 8080

spring:
  application:
    name: MovieRank
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movierank?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "0852"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neet821.movierank.entity
